### ISSUE TITLE
Saving a setting clears all other setting sections in the UI

### ISSUE THREAD

**Issue by choroba** [kyzn/PRC#31]
The saved values are not cleared, fortunately, but it's still confusing.

**Comment by kyzn** [comment]
Thanks for the report! Let me verify it & get back to you.

**Comment by kyzn** [comment]
So I've just took a look at this. Can you confirm the bug you are seeing is:
- You select a personal repository
- Click "save personal repositories"
- It says "saved" but the one you selected is now deselected.

Can you also share the browser you are using while seeing this bug? I'm asking because I wasn't able to reproduce the issue, hence I can't confirm the fix.

**Comment by thibaultduponchelle** [comment]
Hello,

The bug is not exactly what you describe, the item deselected is from **another** section ("Preferred Languages" in your example). You can have the same bug if you click on "Save Preferred Languages" then it's the "Personal Repositories" item that is deselected. Other sections seems to work fine.

I use firefox 73.0.1 on Linux (64bits) but I have the same on a safari browser (phone).

I send you a screencast by email.

Regards :grinning: 

Thibault

**Comment by kyzn** [comment]
Ah! Now I understand what it is. Thanks!

**Comment by kyzn** [comment]
Hi @choroba! @thibaultduponchelle fixed this issue in #34. Can you confirm it's working now?

**Comment by choroba** [comment]
Works fine, thank you!
